# Generated by Django 5.1.6 on 2025-03-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_book_author_book_category_book_distribution_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
